// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt7b5_7Sz3HwKjNmOIlt5RhVqLy8VK2Bo',
    appId: '1:470772611515:web:725297d7ddfdcac413ac9e',
    messagingSenderId: '470772611515',
    projectId: 'qc-college-and-career',
    authDomain: 'qc-college-and-career.firebaseapp.com',
    storageBucket: 'qc-college-and-career.appspot.com',
    measurementId: 'G-YR1PDBH31X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYhR_bc5QhXohjLLMhL_usZqCtmd6rTtI',
    appId: '1:470772611515:android:03f1071c8285b3e413ac9e',
    messagingSenderId: '470772611515',
    projectId: 'qc-college-and-career',
    storageBucket: 'qc-college-and-career.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYz5rFZ6cMPinppVizkNG-_OvpSZe-RJo',
    appId: '1:470772611515:ios:0be6f4d472258a7013ac9e',
    messagingSenderId: '470772611515',
    projectId: 'qc-college-and-career',
    storageBucket: 'qc-college-and-career.appspot.com',
    iosClientId: '470772611515-j750ltp7aklnnpqeii8u1gbgq2hvfsom.apps.googleusercontent.com',
    iosBundleId: 'com.example.qcCollegeandcareer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYz5rFZ6cMPinppVizkNG-_OvpSZe-RJo',
    appId: '1:470772611515:ios:0be6f4d472258a7013ac9e',
    messagingSenderId: '470772611515',
    projectId: 'qc-college-and-career',
    storageBucket: 'qc-college-and-career.appspot.com',
    iosClientId: '470772611515-j750ltp7aklnnpqeii8u1gbgq2hvfsom.apps.googleusercontent.com',
    iosBundleId: 'com.example.qcCollegeandcareer',
  );
}
